In [1]:
# it's machine learning library in python
# built on numpy and matplotlib
# has in-built machine learning models
# very well designed API

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# content
0. An end-to-end scikit learn workflow
1. Getting the data ready
2. Choose the right algorithm/estimator for our problem
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating the model
5. Improve the model
6. save and load a trained model
7. putting it all together!

In [146]:
# let's listify the content
content = ["0. An end-to-end scikit learn workflow",
          "1. Getting the data ready",
          "2. Choose the right algorithm/estimator for our problem",
          "3.Fit the model/algorithm and use it to make predictions on our data",
          "4. Evaluating the model",
          "5. Improve the model",
          "6. save and load a trained model",
          "7. putting it all together!"]
content

['0. An end-to-end scikit learn workflow',
 '1. Getting the data ready',
 '2. Choose the right algorithm/estimator for our problem',
 '3.Fit the model/algorithm and use it to make predictions on our data',
 '4. Evaluating the model',
 '5. Improve the model',
 '6. save and load a trained model',
 '7. putting it all together!']

### 0. End to end scikit learn workflow
[just for complete overview before going step by step]

In [4]:
# 1. get the data ready
disease = pd.read_csv("heart-disease.csv")
disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
x =  disease.drop('target',axis =1) # feature matrix/data/variable
y = disease['target']   # labels

In [6]:
#2. choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# we will keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [7]:
# 3. Fit the model to the trainning data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)


In [8]:
clf.fit(x_train, y_train)

RandomForestClassifier()

In [9]:
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
91    57    1   0       132   207    0        1      168      1      0.0   
182   61    0   0       130   330    0        0      169      0      0.0   
51    66    1   0       120   302    0        0      151      0      0.4   
62    52    1   3       118   186    0        0      190      0      0.0   
276   58    1   0       146   218    0        1      105      0      2.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
183   58    1   2       112   230    0        0      165      0      2.5   
39    65    0   2       160   360    0        0      151      0      0.8   
261   52    1   0       112   230    0        1      160      0      0.0   
153   66    0   2       146   278    0        0      152      0      0.0   
37    54    1   2       150   232    0        0      165      0      1.6   

     slope  ca  thal  
91       2   0     3  
182      2   0     2  
51       1   0     2  
62       1   0     1  
276      1   1     3  
..     ...  ..   ...  
183      1   1     3  
39       2   0     2  
261      2   1     2  
153      1   1     2  
37       2   0     3  

[242 rows x 13 columns]

In [10]:
y_preds = clf.predict(x_test)
y_preds

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [11]:
y_test

144    1
271    0
155    1
118    1
32     1
      ..
31     1
169    0
296    0
12     1
235    0
Name: target, Length: 61, dtype: int64

In [12]:
# 4. evaluate the model on the training data and test data
clf.score(x_train, y_train)

1.0

In [13]:
clf.score(x_test, y_test)

0.8032786885245902

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.81      0.75      0.78        28
           1       0.80      0.85      0.82        33

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.80      0.80      0.80        61



In [15]:
confusion_matrix(y_test, y_preds)

array([[21,  7],
       [ 5, 28]], dtype=int64)

In [16]:
accuracy_score(y_test,y_preds)

0.8032786885245902

In [17]:
# improve the model
# try different amount of n_estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f"trying modelwith {i} esimators...")
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(x_train,y_train)
    print(f"model accuracy on test set: {clf.score(x_test,y_test)*100:.2f}%")
    print(" ")
    

trying modelwith 10 esimators...
model accuracy on test set: 67.21%
 
trying modelwith 20 esimators...
model accuracy on test set: 81.97%
 
trying modelwith 30 esimators...
model accuracy on test set: 75.41%
 
trying modelwith 40 esimators...
model accuracy on test set: 77.05%
 
trying modelwith 50 esimators...
model accuracy on test set: 77.05%
 
trying modelwith 60 esimators...
model accuracy on test set: 75.41%
 
trying modelwith 70 esimators...
model accuracy on test set: 80.33%
 
trying modelwith 80 esimators...
model accuracy on test set: 73.77%
 
trying modelwith 90 esimators...
model accuracy on test set: 77.05%
 


In [18]:
# 6. save a model and load it
import pickle
pickle.dump(clf, open("random_forest_model1.pkl",'wb'))

In [19]:
loaded_model = pickle.load(open("random_forest_model1.pkl", "rb"))
loaded_model.score(x_test, y_test)

0.7704918032786885

### warnings in jupyter notebook

In [20]:
import warnings
#warnings.filterwarnings('ignore')  # ignores the all warnings
warnings.filterwarnings('default') # displays warnings

In [21]:
# checking which scikit learn version you are using
import sklearn
sklearn.show_versions()

C:\Users\HP\anaconda3\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(



System:
    python: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\HP\anaconda3\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.1.1
   setuptools: 49.2.0.post20200714
      sklearn: 0.23.1
        numpy: 1.18.5
        scipy: 1.5.0
       Cython: 0.29.21
       pandas: 1.0.5
   matplotlib: 3.2.2
       joblib: 0.16.0
threadpoolctl: 2.1.0

Built with OpenMP: True


## 1.0 Getting the data ready
1. split the data into features and labels(ususally x and y)
2. filling (also called imputing) or disregrding the missing values
3. converting non-numerical values to numerical values(a.k.a. feature encoding)

In [22]:
disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [23]:
x = disease.drop('target',axis=1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [24]:
y = disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [25]:
# split data into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [26]:
disease.shape,x_train.shape,x_test.shape,y_train.shape,y_test.shape

((303, 14), (212, 13), (91, 13), (212,), (91,))

In [27]:
x.shape,y.shape

((303, 13), (303,))

In [28]:
print(303 * 0.7) # 70%   training set
print(303 * 0.3) # 30%  test set

212.1
90.89999999999999


### 1.1 converting data to numbers

In [29]:
sales = pd.read_csv('car-sales-extended.csv')
sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [30]:
sales.shape

(1000, 5)

In [31]:
sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [32]:
x = sales.drop('Price',axis=1)
x.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [33]:
y = sales['Price']
y.head()

0    15323
1    19943
2    28343
3    13434
4    14043
Name: Price, dtype: int64

In [34]:
x.shape,y.shape

((1000, 4), (1000,))

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((800, 4), (200, 4), (800,), (200,))

In [37]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

ValueError: could not convert string to float: 'Toyota'

In [38]:
sales["Doors"].value_counts() # can be converted to a category type

4    856
5     79
3     65
Name: Doors, dtype: int64

In [39]:
sales["Make"].value_counts()

Toyota    398
Honda     304
Nissan    198
BMW       100
Name: Make, dtype: int64

In [40]:
sales["Colour"].value_counts()

White    407
Blue     321
Black     99
Red       94
Green     79
Name: Colour, dtype: int64

In [41]:
# turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make","Colour","Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',         # list of tuple
                                  one_hot,categorical_features)],
                               remainder = 'passthrough')
transformed_x = transformer.fit_transform(x)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [42]:
transformed_x.shape

(1000, 13)

In [43]:
x.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [44]:
pd.DataFrame(transformed_x).head()

0    1    2    3    4    5    6    7    8    9   10   11        12
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0

In [45]:
dummies = pd.get_dummies(sales[['Make','Colour','Doors']])
dummies.head()

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0      4         0           1            0            0             0   
1      5         1           0            0            0             0   
2      4         0           1            0            0             0   
3      4         0           0            0            1             0   
4      3         0           0            1            0             0   

   Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0            0             0           0             1  
1            1             0           0             0  
2            0             0           0             1  
3            0             0           0             1  
4            1             0           0             0

In [46]:
np.random.seed(42)
x_train,x_test,y_train,y_test = train_test_split(transformed_x,y,test_size=0.2)
model.fit(x_train,y_train)

RandomForestRegressor()

In [47]:
model.score(x_test,y_test)

0.3235867221569877

### 1.2 fixing missing data
1. Fill them with some value(imputation)
2. Remove the samples with missing data altogether

In [57]:
missing_sales = pd.read_csv('car-sales-extended-missing-data.csv')
missing_sales.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [58]:
missing_sales.isna().sum() #missing values

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [59]:
x = missing_sales.drop('Price',axis=1)
y = missing_sales['Price']

In [60]:
# let's covert data to numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make","Colour","Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',         # list of tuple
                                  one_hot,categorical_features)],
                               remainder = 'passthrough')
transformed_x = transformer.fit_transform(x)
transformed_x

ValueError: Input contains NaN

In [61]:
missing_sales['Doors'].value_counts()

4.0    811
5.0     75
3.0     64
Name: Doors, dtype: int64

### option 1: fill missing data with pandas

In [62]:
missing_sales["Make"].fillna('missing',inplace=True)
missing_sales['Colour'].fillna('missing',inplace=True)
missing_sales['Odometer (KM)'].fillna(missing_sales['Odometer (KM)'].mean(),inplace=True)
# missing_sales['Price'].fillna(missing_sales['Price'].mean(),inplace=True)
missing_sales['Doors'].fillna(4,inplace=True)
missing_sales.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [64]:
# remove rows with missing price value
missing_sales.dropna(inplace=True)
missing_sales.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [65]:
missing_sales.shape

(950, 5)

In [67]:
missing_sales.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [68]:
x = missing_sales.drop('Price',axis=1)
y = missing_sales['Price']

In [70]:
# let's covert data to numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make","Colour","Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',         # list of tuple
                                  one_hot,categorical_features)],
                               remainder = 'passthrough')
transformed_x = transformer.fit_transform(missing_sales)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

In [71]:
pd.DataFrame(transformed_x)

0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
1    1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
4    0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
945  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
946  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0   
947  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
948  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
949  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

           14       15  
0     35431.0  15323.0  
1    192714.0  19943.0  
2     84714.0  28343.0  
3    154365.0  13434.0  
4    181577.0  14043.0  
..        ...      ...  
945   35820.0  32042.0  
946  155144.0   5716.0  
947   66604.0  31570.0  
948  215883.0   4001.0  
949  248360.0  12732.0  

[950 rows x 16 columns]

In [79]:
missing_sales['Make'].value_counts()

Toyota     354
Honda      281
Nissan     175
BMW         93
missing     47
Name: Make, dtype: int64

In [77]:
missing_sales['Colour'].value_counts()

White      370
Blue       292
Black       89
Red         81
Green       72
missing     46
Name: Colour, dtype: int64

In [76]:
missing_sales['Odometer (KM)'].value_counts()

131253.237895    48
73869.000000      2
129188.000000     2
220679.000000     1
56534.000000      1
                 ..
101835.000000     1
52054.000000      1
149347.000000     1
229206.000000     1
184320.000000     1
Name: Odometer (KM), Length: 901, dtype: int64

In [75]:
missing_sales['Price'].value_counts()

17076.0    2
17520.0    2
15154.0    2
12402.0    2
7994.0     2
          ..
7350.0     1
7061.0     1
10628.0    1
17065.0    1
6160.0     1
Name: Price, Length: 934, dtype: int64

In [80]:
dummies2 = pd.get_dummies(missing_sales[['Make','Colour','Doors']])
dummies2.head()

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Make_missing  \
0    4.0         0           1            0            0             0   
1    5.0         1           0            0            0             0   
2    4.0         0           1            0            0             0   
3    4.0         0           0            0            1             0   
4    3.0         0           0            1            0             0   

   Colour_Black  Colour_Blue  Colour_Green  Colour_Red  Colour_White  \
0             0            0             0           0             1   
1             0            1             0           0             0   
2             0            0             0           0             1   
3             0            0             0           0             1   
4             0            1             0           0             0   

   Colour_missing  
0               0  
1               0  
2               0  
3               0  
4               0

### option 2: Fill missing values with scikit_learn

In [82]:
data_missing = pd.read_csv('car-sales-extended-missing-data.csv')
data_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [83]:
data_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [84]:
data_missing.dropna(subset=['Price'],inplace=True)
data_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[950 rows x 5 columns]

In [85]:
data_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [86]:
x = data_missing.drop('Price',axis=1)
y = data_missing['Price']

In [88]:
x.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [90]:
from sklearn.impute import SimpleImputer # to fill the missing values
from sklearn.compose import ColumnTransformer
# Fill categorical values with 'missing' and numerical values with mean.
cat_imputer = SimpleImputer(strategy='constant',fill_value='missing')
door_imputer = SimpleImputer(strategy='constant',fill_value=4)
num_imputer = SimpleImputer(strategy='mean')

# define columns
cat_features = ['Make','Colour']
door_features = ['Doors']
num_features = ['Odometer (KM)']

# Create an imputer (something that fills the missing data)
imputer = ColumnTransformer([
    ('cat_imputer',cat_imputer,cat_features),
    ('door_imputer',door_imputer,door_features),
    ('num_imputer',num_imputer,num_features)
])

#Transform the data
filled_x = imputer.fit_transform(x)
filled_x

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [96]:
filled_data = pd.DataFrame(filled_x,
                           columns=['Make','Colour','Doors','Odometer(KM)'])
filled_data.isna().sum()

Make            0
Colour          0
Doors           0
Odometer(KM)    0
dtype: int64

In [97]:
filled_data.head()

Make Colour Doors Odometer(KM)
0   Honda  White     4        35431
1     BMW   Blue     5       192714
2   Honda  White     4        84714
3  Toyota  White     4       154365
4  Nissan   Blue     3       181577

In [100]:
x = filled_data
y = data_missing['Price']

In [101]:
# let's covert data to numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make","Colour","Doors"]

one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',         # list of tuple
                                  one_hot,categorical_features)],
                               remainder = 'passthrough')
transformed_x = transformer.fit_transform(filled_data)
transformed_x

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [105]:
# let's fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(transformed_x,y,test_size=0.2)
model = RandomForestRegressor(n_estimators=100)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.21990196728583944

In [106]:
content

['0. An end-to-end scikit learn workflow',
 '1. Getting the data ready',
 '2. Choose the right algorithm/estimator for our problem',
 '3. Fit the model/algorithm and use it to make predictions on our data Evaluating the model',
 '4. Improve the model',
 '5. save and load a trained model',
 '6. putting it all together!']

### 2. Choose the right algorithm/estimator for our problem
machine learning model: [AKA] ML Algorithm/ ML Estimator
* Classification: Predicting whether a sample is one thing or other
* Regression: Predicting a number

<img src= "ml_map.png"/>

#### 2.1 Picking a machine learning model for a regression problem

In [115]:
from sklearn.datasets import load_boston
boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [118]:
house_data = pd.DataFrame(boston['data'],
                         columns=boston['feature_names'])
house_data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [119]:
house_data['target'] = pd.Series(boston['target'])
house_data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [124]:
house_data.shape, house_data.isna().sum() # check if missing data

((506, 14),
 CRIM       0
 ZN         0
 INDUS      0
 CHAS       0
 NOX        0
 RM         0
 AGE        0
 DIS        0
 RAD        0
 TAX        0
 PTRATIO    0
 B          0
 LSTAT      0
 target     0
 dtype: int64)

In [123]:
# all data is numeric and there is no missing data 
# let' try the Ridge regression model
from sklearn.linear_model import Ridge

#setup the random seed so that the results are regenerative
np.random.seed(42)

#create the data
x = house_data.drop('target',axis=True)
y = house_data['target']

#split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#instantiate the model
model = Ridge()
model.fit(x_train,y_train)

# check the score
model.score(x_test,y_test)

0.6662221670168522

So, How can we improve the score???
* we can try the different model as suggested in the sklearn map<br><br>
Let's try ensemble regressors 
##### ensemble methods:   
goal is to combine thepredictions of several base estimators built with a given learning algorithm in order to improve the generalizability or robustness over a single estimator.


In [130]:
# let's try RandomForest
from sklearn.ensemble import RandomForestRegressor

# setup the random seed (for splitting data into random groups)
np.random.seed(42)

# create the data
x = house_data.drop('target',axis=1)
y = house_data['target']

# split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#instantiate the random forest regressor
rf = RandomForestRegressor()
rf.fit(x_train,y_train)

#evaluate the RandomForest()
rf.score(x_test,y_test)


0.8654448653350507

In [129]:
# for comparison let's check the score of our old Ridge model
model.score(x_test,y_test) #here model instatiated with Ridge model

0.6662221670168522

#### 2.2 Picking a machine learning model for a classification problem

In [138]:
disease = pd.read_csv('heart-disease.csv')
disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [133]:
disease.shape

(303, 14)

In [139]:
#reffering to map: we got to try the linear svm model
from sklearn.svm import LinearSVC

# set up the random seed
np.random.seed(42)

# create the data
x = disease.drop('target',axis=1)
y = disease['target']

# split the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#instantiate the linearsvc
clf = LinearSVC()
clf.fit(x_train,y_train)

# evaluate the model
clf.score(x_test,y_test)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.8688524590163934

let's improve it using ensemble method: RandomForestClassifier

In [141]:
#reffering to map: we got to try the linear svm model
from sklearn.ensemble import RandomForestClassifier

# set up the random seed
np.random.seed(42)

# create the data
x = disease.drop('target',axis=1)
y = disease['target']

# split the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#instantiate the linearsvc
clf = RandomForestClassifier()
clf.fit(x_train,y_train)

# evaluate the model
clf.score(x_test,y_test)

0.8524590163934426

Note:
* when we have structured data, ensemble methods perform better
* when we have unstructerd data, deep learning or transfer learning performs better
    

### 3. Fit the model/algorithm and use it to make predictions on our data 

In [147]:
content

['0. An end-to-end scikit learn workflow',
 '1. Getting the data ready',
 '2. Choose the right algorithm/estimator for our problem',
 '3.Fit the model/algorithm and use it to make predictions on our data',
 '4. Evaluating the model',
 '5. Improve the model',
 '6. save and load a trained model',
 '7. putting it all together!']

### 3.1 Fitting the model to data [training ML model]
* X = Features, Feature variables, data
* Y = labels, tergets, target variables

In [154]:
#reffering to map: we got to try the linear svm model
from sklearn.ensemble import RandomForestClassifier

# set up the random seed
np.random.seed(42)

# create the data
x = disease.drop('target',axis=1)
y = disease['target']

# split the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#instantiate the linearsvc
clf = RandomForestClassifier()

# Fit the data
clf.fit(x_train,y_train)# Training machine learning model or finding patterns in data
# evaluate the model
clf.score(x_test,y_test)

0.8524590163934426

In [155]:
x_train.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
132   42    1   1       120   295    0        1      162      0      0.0   
202   58    1   0       150   270    0        0      111      1      0.8   
196   46    1   2       150   231    0        1      147      0      3.6   
75    55    0   1       135   250    0        0      161      0      1.4   
176   60    1   0       117   230    1        1      160      1      1.4   

     slope  ca  thal  
132      2   0     2  
202      2   0     3  
196      1   0     2  
75       1   0     2  
176      2   2     3

In [156]:
y_train.head()

132    1
202    0
196    0
75     1
176    0
Name: target, dtype: int64

### 3.2 Make predictions using machine learning models

#### 3.2.1 predict() and predict_proba() for classification model

In [157]:
x_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [158]:
y_test.head()

179    0
228    0
111    1
246    0
60     1
Name: target, dtype: int64

use trained model to make predictions.<br>
there are two ways
1. predict()
2. predict_proba()

In [159]:
clf.predict(np.array([1,7,8,3,4]))# this doen't work

ValueError: Expected 2D array, got 1D array instead:
array=[1. 7. 8. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [160]:
x_test.shape

(61, 13)

In [161]:
clf.predict(x_test)  # prediction by ML model

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [162]:
np.array(y_test)   # Ground Truth

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [163]:
# compare predictions to truth labels to evaluate the model
y_preds = clf.predict(x_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [164]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preds)

0.8524590163934426

 Make predictions with predict_proba()

it basically returns predicted probailities of classification label

In [170]:
clf.predict_proba(x_test[:5]) #p(not-heart-disease and heart-disease)

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [171]:
clf.predict(x_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

In [172]:
np.array(y_test[:5])

array([0, 0, 1, 0, 1], dtype=int64)

In [173]:
disease['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

#### 3.2.2 predict() and predict_proba() for regression model

In [175]:
from sklearn.ensemble import RandomForestRegressor

#setting up the seed
np.random.seed(42)

# create the data
x = house_data.drop('target',axis=1)
y = house_data['target']

# split the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#instantiate the model
model = RandomForestRegressor()

# Fit to the data 
model.fit(x_train,y_train)

# make predictions
y_preds = model.predict(x_test)
y_preds

array([23.081, 30.574, 16.759, 23.46 , 16.893, 21.644, 19.113, 15.334,
       21.14 , 20.639, 19.787, 19.541,  8.583, 21.85 , 19.531, 25.851,
       19.759,  8.22 , 45.109, 14.712, 24.548, 23.956, 14.548, 22.944,
       15.023, 14.643, 21.137, 14.153, 19.232, 20.666, 19.588, 23.254,
       33.01 , 20.461, 14.271, 15.889, 34.704, 19.154, 20.85 , 24.395,
       18.978, 29.84 , 45.302, 19.447, 22.234, 13.751, 15.511, 24.612,
       18.729, 28.235, 21.21 , 34.218, 17.271, 26.147, 45.279, 21.924,
       15.532, 32.412, 22.212, 20.453, 25.532, 34.326, 28.795, 18.951,
       27.145, 17.181, 13.534, 23.04 , 28.714, 15.802, 20.451, 27.87 ,
       10.193, 21.507, 22.383,  7.265, 20.089, 45.388, 10.88 , 13.053,
       21.322, 12.366, 20.233,  9.135, 20.052, 26.787, 15.277, 23.267,
       23.613, 17.699, 21.617,  7.921, 19.475, 18.807, 22.386, 19.836,
       38.714, 13.159, 12.476, 13.612, 20.205, 23.832])

In [176]:
np.array(y_test)

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4])

In [179]:
np.mean(y_preds == y_test) # suitable only for classification problem

0.0

In [181]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds)

2.136382352941176

In [182]:
content

['0. An end-to-end scikit learn workflow',
 '1. Getting the data ready',
 '2. Choose the right algorithm/estimator for our problem',
 '3.Fit the model/algorithm and use it to make predictions on our data',
 '4. Evaluating the model',
 '5. Improve the model',
 '6. save and load a trained model',
 '7. putting it all together!']

### 4.0 Evaluating Machine Learning model
there are 3 methods:
* Estimator score method
* Scoring parameter
* metric function

##### 1. Estimator Score Method
provides default evaluation criterion.

In [196]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)
x = disease.drop('target',axis=1)
y = disease['target']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
clf = RandomForestClassifier()
clf.fit(x_train,y_train)

RandomForestClassifier()

In [197]:
clf.score(x_test,y_test)
# Return the mean accuracy on the given test data and labels.

0.8524590163934426

In [198]:
clf.score(x_train,y_train)

1.0

Let's do the same for regression 

In [199]:
from sklearn.ensemble import RandomForestRegressor

#setting up the seed
np.random.seed(42)

# create the data
x = house_data.drop('target',axis=1)
y = house_data['target']

# split the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#instantiate the model
model = RandomForestRegressor()

# Fit to the data 
model.fit(x_train,y_train)


RandomForestRegressor()

In [200]:
model.score(x_test,y_test)
#Return the coefficient of determination R^2 of the prediction.

0.8654448653350507

In [201]:
model.score(x_train,y_train)

0.9763520974033731

##### 2. The `scoring` parameter method
model evaluation using cross-validation